name: CI Test
on: [pull_request]
jobs:
  ci_test:
    strategy:
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false # https://github.community/t/error-the-operation-was-canceled-in-ci/166506/4
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04] # https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4
      - name: List branch dir 
        shell: bash
        run: ls -lR "${{ steps.branch-name.outputs.head_ref_branch }}" 
      - name: Yamllint for info.yml
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "${{ steps.branch-name.outputs.head_ref_branch }}/info.yml"
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: run the all-in-one github-ci.sh
        shell: bash
        run: cd "${{ steps.branch-name.outputs.head_ref_branch }}" && bash github-ci.sh
